### ISSUE TITLE
MWE failure in SHA

### ISSUE THREAD

**Issue by macd** [JuliaDebug/JuliaInterpreter.jl#101]
Currently the tests for the stdlib SHA fail in the interpreter and that causes a latent bug in the runtests.jl of SHA to come up all X's in the interpreter tests.  The problem is that the function ```warn``` is used there, which is undefined, instead of the macro call ```@warn```.  I have submitted a PR for that, and once that is merged, then there are two failures in SHA, both related to sha1.  The following code, when run from the JuliaInterpreter/test directory shows the problem.  Interestingly, if nstmts is set to only 10000 instead of 1000000, then the test passes.

```
using JuliaInterpreter
include("utils.jl")

module SHA_test
    using SHA
    using Test

    sha1_result = "34aa973cd4c4daa4f61eeb2bdbad27316534016f"
    so_many_as_array = repeat([0x61], 1000000)
end

m = SHA_test

ex = quote
    ctx = SHA.SHA1_CTX()
    SHA.update!(ctx, so_many_as_array[1:2*SHA.blocklen(typeof(ctx))])
    SHA.update!(ctx, so_many_as_array[2*SHA.blocklen(typeof(ctx))+1:end])
    hash = bytes2hex(SHA.digest!(ctx))
    @test hash == sha1_result
end

function runex(ex; m=Main, nstmts=10000)
    modexs, _ = JuliaInterpreter.split_expressions(m, ex)
    stack = JuliaStackFrame[]
    for modex in modexs
        frame = JuliaInterpreter.prepare_thunk(modex)
        nstmtsleft = nstmts
        while true
            ret, nstmtsleft = evaluate_limited!(stack, frame, nstmtsleft)
            if isa(ret, Aborted)
                run_compiled(frame)
                break
            elseif isa(ret, Some)
                break
            end
        end
    end
end

runex(ex, m=m, nstmts=1000000)
```

**Comment by timholy** [comment]
Just a comment, your `runex` actually defeats the purpose of that `split_expressions` loop (it's to avoid world-age errors, see #41, definitely one of the trickiest things we've had to face).

In cases where you don't define new structs/methods, you can replace the whole thing with just
```julia
frame = JuliaInterpreter.prepare_thunk(m, ex)
JuliaInterpreter.finish_and_return!(JuliaStackFrame[], frame)
```
where `m` is the module you want to evaluate into.

**Comment by macd** [comment]
Aaah, I see now.  Will do. (I was just using the recipe from #13)

**Comment by timholy** [comment]
Right, but #13 deliberately doesn't put it in a function. By not compiling it, it avoids the world-age errors. (Again, here not an issue anyway.)

**Comment by timholy** [comment]
It may still fail the test due to the `warn`s but the test in this MWE now passes.
