### ISSUE TITLE
More breakpoint automatic modes

### ISSUE THREAD

**Issue by timholy** [JuliaDebug/JuliaInterpreter.jl#102]
Currently `break_on_error[]` can take values `true` or `false`; if true, it breaks on any uncaught exception. Some other things that might be cool:

- break on caught exceptions (can help figure out tricky `try/catch`-induced issues)
- break on test failure
- break on warn

I haven't investigated the feasibility of these, so I have no idea what implementation would look like.

**Comment by KristofferC** [comment]
I don't really think we need more of this than what we currently have.

**Comment by timholy** [comment]
Break on test failure could be nice, but I agree it's not a priority and probably not useful to keep this issue open.
