### ISSUE TITLE
RFC: Allow access to the interpreter state from interpreted code

### ISSUE THREAD

**Issue by KristofferC** [JuliaDebug/JuliaInterpreter.jl#125]
It could be convenient in some situations to be able to access the interpreter state (most relevant is the current frame) from the code that itself is being interpreted. 

This could be done (modulo macro hygiene) by something like

```julia
is_interpreted() = false
current_frame() = nothing

macro interpreted(ex)
    return :(
        if is_interpreted()
            frame = current_frame()
            $ex
        else
             nothing
        end
    )
end
```

One step of creating the `Frame` would then be to replace `is_interpreted()` with `true` and inject a reference to itself instead of `current_frame()`.

One could then do things like

```jl
function f(x)
    print("hello")
    @interpreted print("I am being interpreted, pc currently at $(frame.pc)")
end
```

which could aid in debugging the interpreter itself but might also allow other cool stuff.

There are some considerations:

- Are the use cases strong enough to implement it. I am thinking that e.g. file:line breakpoint support (without Revise) would be possible with this feature fairly trivially with a `@breakpoint` macro that inserts a breakpoint into the current frame.
- With this you can in theory do things that are generally not allowed in julia due to not being optimizable, like local evals. I think that we don't really want people to use the interpreter to enable running non-standard julia code, but it is perhaps unlikely that people will use the interpreter for this.

**Comment by timholy** [comment]
That is an interesting idea. Should we consider renaming the current `@breakpoint` to ensure these wouldn't conflict? Or perhaps use `@bp` for the in-code kind? In honor of the old [Debug.jl](https://github.com/toivoh/Debug.jl).
