### ISSUE TITLE
Binary builds cannot step into source code for stdlib functions due to bad location info

### ISSUE THREAD

**Issue by KristofferC** [JuliaDebug/JuliaInterpreter.jl#144]
Due to https://github.com/JuliaLang/julia/issues/26314 we are getting spurious location info for functions in the stdlib:

```jl
julia> using LinearAlgebra

julia> import JuliaInterpreter.enter_call

julia> enter_call(norm, [1,2])
Frame for norm(itr) in LinearAlgebra at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\LinearAlgebra\src\generic.jl:448
  1 448  1 ─ %1 = (#self#)(itr, 2)
  2 448  └──      return %1
itr = [1, 2]
```

If not too difficult, we could perhaps detect this and rewrite the prefix to `Sys.STDLIB`. Best would of course be to fix it in Base but not sure how hard that is.

**Comment by pfitzseb** [comment]
Should CodeTracking handle this, maybe?
