### ISSUE TITLE
`debug_command`: switch to enums?

### ISSUE THREAD

**Issue by timholy** [JuliaDebug/JuliaInterpreter.jl#160]
In #140 the consensus seems to be to use enums. Should we make the same move in `debug_command`?

**Comment by KristofferC** [comment]
I tried it out a bit but imo the unfortunate truth is that enums are just not that good in Julia. The lack of namespacing is the biggest issue.

I suggest we just swap over to enums since that is consistent with what a lot of the rest of the ecosystem use.

**Comment by timholy** [comment]
Choosing Symbols, see #162
