### ISSUE TITLE
Step out of loop.

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDebug/JuliaInterpreter.jl#175]
Would be convenient to be able to step to the end of a for/while loop and break there.

**Comment by KristofferC** [comment]
Debugger with text editors does this via "Run to cursor".

Gdb has `until`


>Continue running until a source line past the current line, in the current stack frame, is reached. This command is used to avoid single stepping through a loop more than once. It is like the next command, except that when until encounters a jump, it automatically continues execution until the program counter is greater than the address of the jump.
>This means that when you reach the end of a loop after single stepping though it, until makes your program continue execution until it exits the loop. In contrast, a next command at the end of a loop simply steps back to the beginning of the loop, which forces you to step through the next iteration.

Should `n` has the same semantics as `until`?

**Comment by vchuravy** [comment]
Since we have better access to the source-code we maybe could have CFG related commands, like next-block, until, ...

From a IR perspective loops are just backwards branches, so until is neat but requires you to use it in place of next.
