### ISSUE TITLE
subtypes is extremely slow

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDebug/JuliaInterpreter.jl#193]
```
julia> using JuliaInterpreter
       f() = subtypes(Integer)
       @time f()
       @time @interpret f()
  0.027871 seconds (2.32 k allocations: 669.202 KiB)
1204.521373 seconds (408.38 M allocations: 20.456 GiB, 0.30% gc time)
3-element Array{Any,1}:
 Bool    
 Signed  
 Unsigned
```

**Comment by fredrikekre** [comment]
The reason I ran into this is that Documenter uses `subtypes` to determine ordering of build steps etc. However, if you push `subtypes` to `compiled_methods` it is possible to interpret through a Documenter build without any problems, so thats a good thing!

**Comment by pfitzseb** [comment]
Maybe it would make sense to allow the user to push certain functions (or whole modules) into that list as a short term solution until something like https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/204 improves performance. 

That way you could e.g. say that you don't care about what's going on in Base and only interpret user side code. The obvious downside is that higher order functions would be super intransparent, but maybe that's worth it.

**Comment by timholy** [comment]
> allow the user to push certain functions

That's already possible:
```julia
help?> JuliaInterpreter.compiled_methods
  meth ∈ compiled_methods indicates that meth should be run using Compiled rather than recursed into via the interpreter.
```

But perhaps we should push both methods of `subtypes` in `set_compiled_methods`; there's probably not a lot of profit in stepping through them. And users can always `delete!` entries if they really know what they are doing.

**Comment by KristofferC** [comment]
```
julia>        @time @interpret f()
 15.458208 seconds (129.43 M allocations: 4.091 GiB, 2.23% gc time)
3-element Array{Any,1}:
 Bool
 Signed
 Unsigned
```

now (of course with removing the `subtypes` from the compiled method set).

**Comment by KristofferC** [comment]
I don't feel there is anything particularly slow with this specific function here anymore.
