### ISSUE TITLE
Don't blanket ban `Core.Compiler` from interpretation

### ISSUE THREAD

**Issue by vchuravy** [JuliaDebug/JuliaInterpreter.jl#242]
In https://github.com/JuliaDebug/Debugger.jl/issues/150 I wanted to use Debugger.jl to step through a method in `Core.Compiler`. This is currently blocked by https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/6b93e041614b697ed0c05dc68075b863849095c2/src/construct.jl#L119-L121 

It would be awesome if I could use the Debugger for Core.Compiler, but I am okay with having this be a special case (similar to `Revise.track(Core.Compiler)`).

**Comment by timholy** [comment]
It should mostly work; this was a quick hack to get around rare bugs that I didn't have time/motivation to track down. I don't now, either; my advice would be to delete the `Core.Compiler` part of this, run the tests, and then start fixing the things that break. If you get to the point of having this package's tests work, then we might want to also try `test/juliatests.jl` too.
