### ISSUE TITLE
Listeners for global state

### ISSUE THREAD

**Issue by pfitzseb** [JuliaDebug/JuliaInterpreter.jl#261]
It would be really cool if consumers of this package could register event listeners for changes in global state (meaning breakpoints and the `break_on` stuff) to keep the UI synced with JuliaInterpreter's internal state. This mainly comes up if the global state is changed directly with JuliaInterpreter.
Thoughts?

**Comment by KristofferC** [comment]
> This mainly comes up if the global state is changed directly with JuliaInterpreter.

Could you give some examples?

**Comment by pfitzseb** [comment]
Well, Juno provides an interface for adding breakpoints, but you could still use `JuliaInterpreter.breakpoint(sin)`, and then there's no way for Juno to know that something changed. Same if e.g. breakpoints get invalidated because of method redefinition (not entirely sure if that's possible right now or after your breakpoint rework).

**Comment by oxinabox** [comment]
This would also be useful for 
making it possible to do #306 in a package 
(https://github.com/oxinabox/MixedModeDebugger.jl)
because in response to a breakpoint being added or removed or enabled or disabled,
it needs to generate some Cassette overdubs.

As such I might take a short at this.
