### ISSUE TITLE
manipulating breakpoints

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaDebug/JuliaInterpreter.jl#278]
It would be nice to have an API to list existing breakpoints, to make it easier to enable and disable them. I see there are enable and disable functions, but having added a breakpoint in the debugger it's not clear how to get a `BreakpointRef` to pass to them. Might just be a documentation issue.

**Comment by JeffBezanson** [comment]
Ah, I see `breakpoints()` already exists, so that can just be documented.

**Comment by KristofferC** [comment]
See https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/259 which should make this quite a lot more convenient.

**Comment by KristofferC** [comment]
closed by https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/259
