### ISSUE TITLE
JuliaInterpreter Questions

### ISSUE THREAD

**Issue by Daniel-Fermoselle** [JuliaDebug/JuliaInterpreter.jl#295]
Hello, I am using JuliaInterpreter for my master thesis project and I have 2 main questions.
1 - Is it possible to get a frame for all the code that is written within the Atom text editor, or is it only possible to get a frame for a function call with methods like JuliaInterpreter.enter_call(). For example, if I want to get a frame for the code in the image below can I only do that if I write a function for it? If not are you planning on implementing it? Is it easy for me to implement it based on your code?
![3](https://user-images.githubusercontent.com/17110877/58750337-f86fb580-8488-11e9-9c89-5e44b5704cd2.PNG)

2 - At the moment, I am using the line number of each frame to achieve one of the goals of my project. However, it would be better if I could use the range of a frame within the text editor. To better understand the problem, see the example images attached. In this example I would want to get the range of all expressions. For instance, for a = 1 and b = 2, besides getting their line number with JuliaInterpreter.whereis(frame) since the resulting line will always be 3, I would also want to get the expressions range. Is this possible? If not are you planning on implementing it? Is it easy for me to implement it based on your code?

![1](https://user-images.githubusercontent.com/17110877/58750342-045b7780-8489-11e9-98e1-d62262b3814e.PNG)
![2](https://user-images.githubusercontent.com/17110877/58750344-06253b00-8489-11e9-93d3-0faf4dd6a827.PNG)

Thank you for your time.

**Comment by timholy** [comment]
Check out `JuliaInterpreter.prepare_thunk`.

**Comment by Daniel-Fermoselle** [comment]
Hello again,
Thank you for your fast answer. For question 2, is there anything I can do? Is there a function call that returns the range of an expression within the text editor? Am I able to distinguish the line range between a = 1 and b = 2 in this image?
![1](https://user-images.githubusercontent.com/17110877/58754357-2c1d0080-84c6-11e9-89bd-874494c1d298.PNG)

**Comment by KristofferC** [comment]
If you are talking about column ranges then not really. The base parser doesn't expose this and you need something like CSTParser.jl.

**Comment by Daniel-Fermoselle** [comment]
Thank you all.
