### ISSUE TITLE
Expected performance

### ISSUE THREAD

**Issue by dfdx** [JuliaDebug/JuliaInterpreter.jl#336]
Recently I've rewritten [Yota's tracer](https://github.com/dfdx/Yota.jl/blob/master/src/trace/interp.jl) from Cassette to JuliaInterpreter which I found more flexible and much easier to debug. However, the cost of this move is extreme slowdown - a simple neural network which usually takes ~1 second now takes almost 10 minutes in tracer, and most of this time is due to JuliaInterpreter (I can provide exact code and timings if needed). 

I see that a lot of work [is being done](https://github.com/JuliaDebug/JuliaInterpreter.jl/labels/performance) to improve the situation, but in the end what slowdown should we expect? Is it 5x, 10x or 100x compared to runtime of normal call (including compilation time to make it fair)?

**Comment by KristofferC** [comment]
We are at a point where the current strategy doesn't have any real low hanging fruits left (at least not at the order of magnitude level). More drastic things like https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/309 will likely improve the situation but it is not clear by how much and if (or at all) that will ever be implemented.

**Comment by dfdx** [comment]
Got it, thanks! 
Just for my own reference in future, here's a simple snippet to test my use case: 

```
using JuliaInterpreter
using BenchmarkTools

```
