### ISSUE TITLE
Debugger simpler Step into Function

### ISSUE THREAD

**Issue by rveltz** [JuliaDebug/JuliaInterpreter.jl#348]
Hi,

I have been using the debugger part of Juno lately and it works very well!

However, I quickly needed a way to Step into function without going through evaluating all the arguments. This is especially cumbersome when the number of (keyword) arguments is large. Is there a way to Step into Function in such a way?

Thank you for your work,

Best regards

**Comment by timholy** [comment]
It should step through the keyword arg stuff automatically, but perhaps you have a keyword arg function for which that doesn't work. Can you supply an example (aka, test case)?

**Comment by pfitzseb** [comment]
I think this is about cases like
```
foo(bar, baz, buzz) = bar + baz + buzz
outer(x,y,z) = foo(sin(x), sin(y), sin(z))
@enter outer(1,2,3)
```
where you have to `se` three times before you can step into the call to `foo`.

**Comment by rveltz** [comment]
exactly and when you have many keyword arguments, this can be tedious

**Comment by KristofferC** [comment]
Dup of https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/360
