### ISSUE TITLE
`FrameCode` printing can be misleading when including multiline statement

### ISSUE THREAD

**Issue by aviatesk** [JuliaDebug/JuliaInterpreter.jl#357]
```julia
julia> frame = prepare_thunk(Main, :(map(x -> 2^x, 1:1000)));
julia> finish!(frame, true)
julia> frame
Frame for JuliaInterpreter
⋮
   8 0  │   %3 = (Core.svec)()
   9 0  │   %4 = (Core.svec)(%2, %3)
  10 0  │        $(Expr(:method, false, :(%4), CodeInfo(
#118 = #118
```

but this should look like:

```julia
Frame for JuliaInterpreter
⋮
   8 0  1:1000
   9 0  map(%7, %8)
  10 0  return %9
#118 = #118
```

This happens because [`framecode_lines`](https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/master/src/utils.jl#L314) took a `show` string of `CodeInfo` verbatim.

We can take an easy fix like [what have been done in this branch](https://github.com/aviatesk/JuliaInterpreter.jl/commit/f7d374f16506e161fa07d7dd41869a5fb69ccdb6), but then we lose some fancy printing tweaks in [`show_ir`](https://github.com/JuliaLang/julia/blob/master/base/show.jl#L1869) ... (i.e. we need to show basic block printing, replacing slots with slotnames by ourselves)

Not sure what is the best way to fix this, so I posted this as an issue here.

**Comment by timholy** [comment]
Works now. Maybe #410?
