### ISSUE TITLE
Debugger simpler Step into Function

### ISSUE THREAD

**Issue by rveltz** [JuliaDebug/JuliaInterpreter.jl#360]
Hi,

I have been using the debugger part of Juno lately and it works very well!

However, I quickly needed a way to Step into function without going through evaluating arguments. This is especially cumbersome when the number of (keyword) arguments is large. Is there a way to Step into Function in such a way?

Thank you for your work,

Best regards

**Comment by timholy** [comment]
Can you give concrete examples? Are you talking about `f(g(x), h(y))` and wanting to skip `g` and `h`, or are you talking about `f(x)` when `f` has keyword arguments? The latter should already be handled (see #190), but if it's not please give some reproducible examples.

**Comment by rveltz** [comment]
Hi, this is a repost of https://github.com/JunoLab/Juno.jl/issues/417

I am interested in the last case `f(a, b, c, d)`, so I guess it is done in you reference.

In Juno, before, accessing the function itself, you have to evaluate all the fields. A shortcut would be super helpful ( I think). However the guys in JunoLab closed the issue and ask me to out it here :woman-shrugging:

I am confused...

**Comment by timholy** [comment]
You'll have to copy/paste an example that I can actually run. For example with
```julia
h(x; b=rand()) = 1

function g(n)
    s = 0
    for i = 1:n
        s += h(i)
    end
    return s
end
```
I'm not seeing your concern.

**Comment by rveltz** [comment]
You are right, I was not very clear to say the least. I am looking for a button in Juno to do this but I can certainly do it in the REPL, silly me...

**Comment by KristofferC** [comment]
I think the idea is that if you have a call like

```
f(g(), h(), i(), j())
```

then it is quite often that you want to step into `f` without having to manually step over the argument calls.

**Comment by timholy** [comment]
Might need https://github.com/JuliaLang/julia/issues/31162. Curiously, this is a case where Rebugger's original (and still working) `Alt-e` interface makes it much easier:

```julia
f(x, y, z) = x + y + z

function g()
    return f(sin(rand()), cos(3), sqrt(7))
end
```
one gets
![image](https://user-images.githubusercontent.com/1525481/73065568-7e51ce00-3e69-11ea-8727-77fef9a9a260.png)
(now hit Alt-e) directly to
![image](https://user-images.githubusercontent.com/1525481/73065630-a5a89b00-3e69-11ea-816e-b1cac8470e1d.png)

**Comment by pfitzseb** [comment]
Oh, VSCode's debugger has this functionality now (via Right Click -> Step Into Targets):
![image](https://user-images.githubusercontent.com/6735977/102509101-6e953680-4086-11eb-9094-1baf4a3e4b05.png)

**Comment by KristofferC** [comment]
This is implemented now here and in Debugger.jl with the `sl` command. Using the example in https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/360#issuecomment-578091963

```jl
julia> @enter g()
In g() at REPL[3]:1
 1  function g()
>2      return f(sin(rand()), cos(3), sqrt(7))
 3  end

About to run: (rand)()
1|debug> sl
In f(x, y, z) at REPL[2]:1
>1  f(x, y, z) = x + y + z
```

**Comment by HusterRichard** [comment]
> Oh, VSCode's debugger has this functionality now (via Right Click -> Step Into Targets): ![image](https://user-images.githubusercontent.com/6735977/102509101-6e953680-4086-11eb-9094-1baf4a3e4b05.png)

Hello，I'm interested in how to show the statement of code in VScode?
Just like below picture:
![image](https://user-images.githubusercontent.com/20569618/165419447-98783747-b9f1-467e-b22d-34ee59e4b0a7.png)
