### ISSUE TITLE
Provide a method to run a string of code in the debugger

### ISSUE THREAD

**Issue by davidanthoff** [JuliaDebug/JuliaInterpreter.jl#362]
And another request for a high level API addition: it would also be great if there was a function that simply accepts a string of code and runs that in the debugger. So that instead of writing `@interpret foo()`, I could write `interpret("foo()")`. That would also make the VS Code integration a lot easier.

**Comment by davidanthoff** [comment]
Similar to #361, I think my ideal API would be something like `prepare_global_frame_from_src(code::AbstractString)`, and then that returns something that I can pass to `debug_command`.

**Comment by timholy** [comment]
You mean kind of like `JuliaInterpreter.enter_call_expr(Meta.parse(Main, str))`? :smile:

**Comment by davidanthoff** [comment]
Ok, I figured this out, thanks for the help!
