### ISSUE TITLE
Make global breakpoints work

### ISSUE THREAD

**Issue by davidanthoff** [JuliaDebug/JuliaInterpreter.jl#368]
Right now both Juno and VS Code manually insert breakpoints for global level statements, with code that looks like [this](https://github.com/JunoLab/Atom.jl/pull/269/files#diff-74535f4e40b9f850dc9f0d02ae8feb04R80).

I think it would be great if that wasn't necessary :) I'm already calling `breakpoint` for those breakpoints, and ideally that would be enough and no additional hacking on the AST was necessary.

The hacks we have right now also don't work for conditions on the breakpoints.

CC @pfitzseb

**Comment by KristofferC** [comment]
First step is to enable them by removing https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/08333287554a7aa54df447ee13dd465c87afef8b/src/types.jl#L107.

Then figure out if there is any fallout.
