### ISSUE TITLE
eval_rhs cannot eval a Module

### ISSUE THREAD

**Issue by cstjean** [JuliaDebug/JuliaInterpreter.jl#377]
My long and complicated macro that implements a PPL is unrevisable now. It's used at the top-level, and when I modify its invocation, Revise triggers:

```julia
  MethodError: no method matching eval_rhs(::typeof(JuliaInterpreter.finish_and_return!), ::JuliaInterpreter.Frame, ::Module)
Closest candidates are:
  eval_rhs(::Any, ::Any, ::Expr) at /home/cst-jean/.julia/packages/JuliaInterpreter/hyz9z/src/interpret.jl:368
Stacktrace:
 [1] lookup_or_eval(::Any, ::JuliaInterpreter.Frame, ::Any) at /home/cst-jean/.julia/packages/JuliaInterpreter/hyz9z/src/interpret.jl:111
while evaluating
```

I do believe that it used to work, FWIW. I don't have the energy/time to make a MWE demonstrating the issue, but fortunately there is an easy solution:

```julia
julia> @eval JuliaInterpreter eval_rhs(::typeof(JuliaInterpreter.finish_and_return!), ::JuliaInterpreter.Frame, m::Module) = m
eval_rhs (generic function with 2 methods)
```

Would that be an acceptable PR? I understand that it is unsatisfying not understanding the root cause, so I would understand a negative answer...

**Comment by pfitzseb** [comment]
Is this only on Julia master? If so, dup of #376.

**Comment by cstjean** [comment]
It's on 0.7.10. I've seen it since at least one week. I really doubt that it's a dup, it looks different.

**Comment by cstjean** [comment]
We took out our fix and it seems to be working properly now...
