### ISSUE TITLE
ERROR: type Union has no field name

### ISSUE THREAD

**Issue by zenna** [JuliaDebug/JuliaInterpreter.jl#435]
I don't have a MWE but Debugger is failing on some of my code due to the fact that in `commands.jl`, in

`is_kw = isa(scope, Method) && comp(String(Base.unwrap_unionall(Base.unwrap_unionall(scope.sig).parameters[1]).name.name), "#kw")`

`Base.unwrap_unionall(Base.unwrap_unionall(scope.sig).parameters[1])` is a Union

```
julia> @enter x(ω)
scope = (f::Union{Distribution, Mv, Variable})(ω::Ω) where Ω<:AbstractΩ in OmegaCore.Var at /home/zenna/repos/OmegaCore.jl/src/var/dispatch.jl:14
Base.unwrap_unionall(scope.sig) = Tuple{Union{Distribution, Mv, Variable},Ω<:AbstractΩ}
(Base.unwrap_unionall(scope.sig)).parameters = svec(Union{Distribution, Mv, Variable}, Ω<:AbstractΩ)
(Base.unwrap_unionall(scope.sig)).parameters[1] = Union{Distribution, Mv, Variable}
ERROR: type Union has no field name
```

I suspect it's something to do with the fact that I'm providing a call method for a union in `f`

**Comment by timholy** [comment]
Thanks for the report and the diagnosis of the problem. Can you perhaps uncomment https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/2f5f80034bc287a60fe77c4e3b5a49a087e38f8b/src/interpret.jl#L435-L436 and isolate a test case? Fixes that come with tests are oh-so-much-more-valuable than bare fixes, especially since in the long run this package is likely to be heavily refactored to execute a more efficient format than Julia's current lowered IR.

That said, if you can't trace it down, we should just fix this.

**Comment by melonedo** [comment]
I have a MWE with Debugger.jl. Simply execute `s` once on `0x0 == UInt8('\t')` will trigger this issue.
```julia
julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PKG_SERVER = https://mirrors.bfsu.edu.cn/julia

julia> using Debugger # v0.7.0

julia> foo() = 0x0 == UInt8('\t')
foo (generic function with 1 method)

julia> @enter foo()
failed to highlight code, TypeError(Symbol("keyword argument"), :bold, Union{Nothing, Bool}, :nothing)
failed to highlight code, TypeError(Symbol("keyword argument"), :bold, Union{Nothing, Bool}, :nothing)
In foo() at REPL[3]:1
>1  foo() = 0x0 == UInt8('\t')

About to run: (UInt8)('\t')
1|debug> s
ERROR: type Union has no field name
Stacktrace:
 [1] UInt8(c::Char)
   @ Base char.jl:174
 [2] foo()
   @ Main REPL[3]:1
```
