### ISSUE TITLE
Can not step into body of `@error` because "UndefVarError: REPL[1] not defined"

### ISSUE THREAD

**Issue by melonedo** [JuliaDebug/JuliaInterpreter.jl#535]
MWE:

```julia
using JuliaInterpreter
f() = @error "ex"
frame = JuliaInterpreter.enter_call(f)
debug_command(frame, :c)
#=
ERROR: UndefVarError: REPL[17] not defined
Stacktrace:
 [1] collect_args(recurse::Any, frame::Frame, call_expr::Expr; isfc::Bool)
   @ JuliaInterpreter C:\Users\melonedo\.julia\packages\JuliaInterpreter\Q7nmG\src\interpret.jl:60
=#
```

I expect it to log some message instead of crashing.

The issue is identical to #441, but since I am using 0.9.13, it should have already been fixed.

**Comment by timholy** [comment]
`git bisect`s to #532. AFAICT this is because it seems to largely revert #442. The test is still there and passes, so the test wasn't strenuous enough. The test here catches it, and has been added in #540. Thanks, @melonedo!
