### ISSUE TITLE
Latency on first call unacceptable

### ISSUE THREAD

**Issue by timholy** [JuliaDebug/JuliaInterpreter.jl#57]
This package loads quite quickly:
```julia
julia> @time(using JuliaInterpreter)
  0.146759 seconds (178.45 k allocations: 11.704 MiB, 3.25% gc time)
```
but the first usage is slow:
```julia
julia> @time @interpret 1+1
  3.875351 seconds (1.34 M allocations: 65.670 MiB, 1.16% gc time)
2
```
Especially if Revise is going to be transitioning to using JuliaInterpreter for signature-extraction, this needs improvement.

**Comment by KristofferC** [comment]
Sadly, with the exception of actual precompilation into the sysimg,  I have found very few "tricks" that can be used to help with time to first call. `@nospecialize` does help some in extreme cases (https://github.com/carlobaldassi/ArgParse.jl/pull/76) but in general seems to be in the noise margin.

Why is first call timing for Revise important? I usually notice a bit of a stutter the first time Revise activates but do you just think that 4 seconds is too long?

Locally I get

```
> @time @interpret 1+1
  1.266199 seconds (1.39 M allocations: 69.039 MiB, 0.77% gc time)
```

but this might just be hardware difference.

**Comment by timholy** [comment]
The reason it matters for Revise is that sometime people still restart their sessions frequently. If the first time Revise evaluates a diff there's a multi-second delay, that's frustrating. (I've gotten a fair number of "reduce the overhead" issues filed in both Revise & Rebugger.)

**Comment by timholy** [comment]
It's also worth saying that these hardware differences are a big deal. Mine is twice the latency of yours, and I've had folks report issues that revealed theirs was twice mine. 8s is a long time to wait.
