### ISSUE TITLE
Debugger broke on "Symbol()"

### ISSUE THREAD

**Issue by joa-quim** [JuliaDebug/JuliaInterpreter.jl#571]
See image. (Julia 1.9.0rc2)

![image](https://user-images.githubusercontent.com/537321/233643841-b99b42af-9ba6-461e-984c-645759e1f668.png)

**Comment by KristofferC** [comment]
Doing it in the REPL:

```
julia> using Debugger

julia> @run Symbol()
Symbol("")
```

**Comment by pfitzseb** [comment]
The VS Code extension doesn't really support 1.9 yet.

**Comment by timholy** [comment]
I'm expecting 🤞 release next week. Anything we can do to help? I don't have time to dive into VS Code internals but if there's any work here...

**Comment by pfitzseb** [comment]
I suspect this happens because we're vendoring an outdated version of JuliaInterperter. Will look into it over the weekend.

**Comment by timholy** [comment]
Gotcha, thanks. Yes, before #568 there was a lot that was broken, and depending on how outdated your version is there may be more.

**Comment by KristofferC** [comment]
I'm going to close this since it seems JuliaInterpreter works fine here.
