### ISSUE TITLE
Error only while using the debugger in VSCode

### ISSUE THREAD

**Issue by sophia-wright-blue** [JuliaDebug/JuliaInterpreter.jl#574]
hello - I'm able to run a script in VSCode, but get an error only while using the VSCode debugger - I have shared the details along with a reproducer on the Julia VSCode extension repo here:

https://github.com/julia-vscode/julia-vscode/issues/3349

and one of the contributors was kind enough to look into the error and has ID'ed the root cause as an issue with JuliaInterpreter - the stack trace of the error are in the comment here:

https://github.com/julia-vscode/julia-vscode/issues/3349#issuecomment-1641634133

it'd help us out greatly if we could get some feedback on resolving the issue - thank you so much!

**Comment by timholy** [comment]
Sorry this took so long to fix. New version coming: https://github.com/JuliaRegistries/General/pull/89435

**Comment by sophia-wright-blue** [comment]
thank you so much - I'll test this right away

**Comment by timholy** [comment]
You may want to use `A` of smaller size (e.g., 128x128), the interpreter is slow.

**Comment by sophia-wright-blue** [comment]
hello @timholy - quick update on this - the julia-vscode extension has been updaed to use a recent version the Interpreter and the issue has been resolved - thank you so much for your help!

**Comment by timholy** [comment]
Thanks for the feedback, that means a lot!

**Comment by sophia-wright-blue** [comment]
absolutely - one final question for you - you mentioned that the interpreter is slow - I'm finding the difference to be many orders of magnitude: 10 min while debugging vs 30 seconds to run the same script normally - is there any way to improve on that time?

**Comment by sophia-wright-blue** [comment]
perfect - I'll go throught the threads on Discourse - thank you so much again!

**Comment by pfitzseb** [comment]
There's also a bit of documentation [here](https://www.julia-vscode.org/docs/dev/userguide/debugging/#Settings-to-speed-up-the-debugger).
