### ISSUE TITLE
Segfaults

### ISSUE THREAD

**Issue by timholy** [JuliaDebug/JuliaInterpreter.jl#580]
While I don't see segfaults locally (at least not very often), they show up on CI. This run must be some kind of record: https://github.com/JuliaDebug/JuliaInterpreter.jl/actions/runs/5825425653/

Merits a look

**Comment by vtjnash** [comment]
There was a wrong `ccall(:time)` signature that would corrupt one random pointer of memory. Fixed by https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/615
