### ISSUE TITLE
Improve performance via JuliaSyntax

### ISSUE THREAD

**Issue by ShalokShalom** [JuliaDebug/JuliaInterpreter.jl#588]
According to [some comment on the forum](https://discourse.julialang.org/t/video-how-to-reduce-julias-latency/100298/12?u=shalokshalom), is it possible that the interpreter does benefit from running the Julia level optimizations before executing, and cutting out the LLVM compilation time. 

The introduction of [JuliaSyntax](https://github.com/JuliaLang/JuliaSyntax.jl) could make it easier to trace the optimized Julia IR back to the source code.

**Comment by timholy** [comment]
We need JuliaSyntax to also handle lowering before this is viable. Right now it "only" handles parsing (that alone was a huge engineering feat).

**Comment by ShalokShalom** [comment]
Could we leave this open, and leave a link to the place where we can track the implementation of lowering, once it is in the works?

**Comment by timholy** [comment]
No need. The people who might implement it are fully aware of the issue. And you can always link to a closed issue.
