### ISSUE TITLE
incorrect model of :method for evaluate_methoddef

### ISSUE THREAD

**Issue by vtjnash** [JuliaDebug/JuliaInterpreter.jl#632]
Precompile script is broken on julia master, e.g. see https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2024-06/13/DocumenterTools.primary.log
```
[0KERROR: LoadError: UndefVarError: `private` not defined in `JuliaInterpreter.var"#Internal".Private`
[0KStacktrace:
[0K  [1] evaluate_methoddef(frame::JuliaInterpreter.Frame, node::Expr)
[0K    @ JuliaInterpreter ~/.julia/packages/JuliaInterpreter/vszNQ/src/interpret.jl:324
```
@Keno was this your change?

**Comment by Keno** [comment]
Possibly. I ran PkgEval and fixed all issues reported, but JuliaInterpreter may have been broken for unrelated reasons and seems like the kind of package that may need a fix. @aviatesk already did one

**Comment by KristofferC** [comment]
https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/630
