### ISSUE TITLE
next_line! doesn't really seem to work properly

### ISSUE THREAD

**Issue by KristofferC** [JuliaDebug/JuliaInterpreter.jl#73]
```jl
julia> function f(x)
           x = 2
           x = 3
           x = 4
       end
f (generic function with 1 method)

julia> frame = JuliaInterpreter.enter_call(f, 1);

julia> stack = [frame];

julia> JuliaInterpreter.linenumber(frame)
2

julia> JuliaInterpreter.next_line!(stack, frame)
JuliaProgramCounter(5)

julia> JuliaInterpreter.linenumber(frame) # Why are we not on line 3 now?
4
```

**Comment by pfitzseb** [comment]
Works fine if there's actually something happening on each line, afaict.

**Comment by KristofferC** [comment]
It's the 

https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/8ee582909d511023dd91c50bc202f020b43036f1/src/interpret.jl#L677

that advances us and this seems intentional. Not sure why we are not stopping at e.g. assignments?

**Comment by KristofferC** [comment]
Perhaps because there is a bunch of assignments that dont do anything inserted by the compiler. Anyway, not that important.
