### ISSUE TITLE
Renaming?

### ISSUE THREAD

**Issue by timholy** [JuliaDebug/JuliaInterpreter.jl#78]
As we near release, perhaps we should think a bit more about naming. Here are a few potential gotchas, without yet proposing specific fixes:

* `frame.code.code.code` is awkward
* are `JuliaFrameCode` and `JuliaStackFrame` sufficient clear as to their purpose?
* `step_expr!` vs `_step_expr!`
* we have various `prepare_*` but then also `build_frame`
* we have both `isfoo` and `is_foo` names

**Comment by KristofferC** [comment]
Maybe this can be closed? I like the current names.

**Comment by timholy** [comment]
Closed by #124
