### ISSUE TITLE
Suspicious error throwing for CodeInfo

### ISSUE THREAD

**Issue by KristofferC** [JuliaDebug/JuliaInterpreter.jl#83]
This `error` call in 

https://github.com/JuliaDebug/JuliaInterpreter.jl/blob/8ee582909d511023dd91c50bc202f020b43036f1/src/interpret.jl#L169-L172

stood out  to me as a bit suspicious when reading the code.

Should this just be an `@assert !(f isa CodeInfo)` and the call to `finish_and_return!` removed?

**Comment by timholy** [comment]
This is a sentinel so I can learn how to handle this properly, but I've never seen an example of it tripping. (This derives from legacy ASTInterpreter2 code, modified by me but I'm not sure if the modifications make sense.) I was hoping to encounter it sometime and then I could examine the inputs and figure out how to handle it properly.

**Comment by timholy** [comment]
Sentinel removed in #124
