### ISSUE TITLE
Doctests are failing

### ISSUE THREAD

**Issue by KristofferC** [JuliaDebug/JuliaInterpreter.jl#87]
Some doctests are failing but we are showing a lot of internals in the output for e.g. `JuliaStackFrame´ so it is perhaps not worth fixing these until something like https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/34 has been merged.

Also, the automatic doctest fixer in Documenter fails to fix these so I should probably figure out why.

**Comment by timholy** [comment]
Fixed by #88
