### ISSUE TITLE
MWE of failure in test for show

### ISSUE THREAD

**Issue by macd** [JuliaDebug/JuliaInterpreter.jl#98]
The test of ```redirect_stdout``` fails because ```stdout``` doesn't really appear to be redirected. Note that this happens for ```redirect_stderr``` as well.

```
ex = quote
    rdout, wrout = redirect_stdout()
    @test wrout === stdout
end
```

**Comment by timholy** [comment]
Oh, drat. Here's the underlying problem:
```julia
julia> x = 5
5

julia> function foo()
           global x
           x = 7
           return nothing
       end
foo (generic function with 1 method)

julia> using JuliaInterpreter

julia> @interpret foo()

julia> x
5
```
Obviously, compiled mode doesn't have this problem.

This was a *really* good one to catch, thanks a ton @macd.
